// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otxggutfsyopaqeitcmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90eGdndXRmc3lvcGFxZWl0Y215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDc4NjAsImV4cCI6MjA2NDMyMzg2MH0.gLR-yZ7T_RE37LPgho1lM3uwG4oJDwKko8vnank8po0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);